apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: three-tier
spec:
  type: ClusterIP

  selector:
    app: sqlserver

  ports:
    - name: sql
      port: 1433
      targetPort: 1433